swagger: '2.0'
info:
  title: MICrONS Ariadne NDA Anatomy API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /experiments:
    get:
      tags: [Experiments]
      security:
        - bearer: []
      summary: Get all experiments
      responses:
        200:
          description: Return experiments
          schema:
            type: array
            items:
              $ref: '#/definitions/Experiment'

  /samples:
    get:
      tags: [Samples]
      security:
        - bearer: []
      summary: Get all samples
      parameters:
        - name: experiment
          description: Specify an experiment name/id
          in: query
          type: string
          required: true
      responses:
        200:
          description: Return samples
          schema:
            type: array
            items:
              $ref: '#/definitions/Sample'

  /datasets:
    get:
      tags: [Datasets]
      security:
        - bearer: []
      summary: Get all datasets
      parameters:
        - name: experiment
          description: Specify an experiment name/id
          in: query
          type: string
          required: true
        - name: sample
          description: Specify a sample name/id
          in: query
          type: string
          required: true
      responses:
        200:
          description: Return datasets
          schema:
            type: array
            items:
              $ref: '#/definitions/Dataset'

  /channels:
    get:
      tags: [Channels]
      security:
        - bearer: []
      summary: Get channels for a dataset
      parameters:
        - name: experiment
          description: Specify an experiment name/id
          in: query
          type: string
          required: true
        - name: sample
          description: Specify a sample name/id
          in: query
          type: string
          required: true
        - name: dataset
          description: Specify a dataset name/id
          in: query
          type: string
          required: true
      responses:
        200:
          description: Return channels
          schema:
            type: array
            items:
              $ref: '#/definitions/Channel'

  /channel_metadata:
    get:
      tags: [ChannelMetadatas]
      security:
        - bearer: []
      summary: Get channel_metadata
      parameters:
        - name: experiment
          description: Specify an experiment name/id
          in: query
          type: string
          required: true
        - name: sample
          description: Specify a sample name/id
          in: query
          type: string
          required: true
        - name: dataset
          description: Specify a dataset name/id
          in: query
          type: string
          required: true
        - name: channel
          description: Specify a channel name/id
          in: query
          type: string
          required: true
      responses:
        200:
          description: Return channel_metadatas
          schema:
            type: array
            items:
              $ref: '#/definitions/ChannelMetadata'

  /entity_feature:
    get:
      tags: [EntityFeatures]
      security:
        - bearer: []
      summary: Get all entity_features
      responses:
        200:
          description: Return entity features
          schema:
            type: array
            items:
              $ref: '#/definitions/EntityFeature'

  /data:
    get:
      tags: [Data]
      security:
        - bearer: []
      summary: Get all data
      produces:
        - image/png
        - image/tiff
      parameters:
        - name: experiment
          description: Specify an experiment name/id
          in: query
          type: string
          required: true
        - name: sample
          description: Specify a sample name/id
          in: query
          type: string
          required: true
        - name: dataset
          description: Specify a dataset name/id
          in: query
          type: string
          required: true
        - name: x
          description: Specify x value
          in: query
          type: integer
          required: true
        - name: y
          description: Specify y value
          in: query
          type: integer
          required: true
        - name: z
          description: Specify z value
          in: query
          type: integer
          required: true
        - name: width
          description: Specify width
          in: query
          type: integer
          required: true
        - name: height
          description: Specify height
          in: query
          type: integer
          required: true
        - name: channel
          description: Specify a channel name/id
          in: query
          type: string
          required: true
        - name: format
          description: Specify image format
          in: query
          type: string
          required: false
      responses:
        200:
          description: Return data
          #schema:
            #type: array
            #items:
              #$ref: '#/definitions/Data'

  /mask:
    get:
      tags: [Masks]
      security:
        - bearer: []
      summary: Get all masks
      responses:
        200:
          description: Return masks
          schema:
            type: array
            items:
              $ref: '#/definitions/Mask'

definitions:
  Experiment:
    type: object
  Sample:
    type: object
  Dataset:
    type: object
  Channel:
    type: object
  ChannelMetadata:
    type: object
  EntityFeature:
    type: object
  Data:
    type: object
  Mask:
    type: object
